##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
- hosts: all
  user: vagrant
  sudo: yes

  vars_files:
    - group_vars/all.yml

  roles:
    - common

- hosts: cap-server
  user: vagrant
  sudo: yes

  vars_files:
    - group_vars/all.yml

  roles:
    - web
    - php5
    - mariadb
    - composer
