---

- name: Apache2 | Install required packages
  apt: pkg=apache2
  tags: apache2

- name: Apache2 | Active module rewrite
  command: a2enmod rewrite
  tags: apache2
  notify: Restart apache

- name: Apache2 | Add vhost for exercise-1
  template: src=vhost-exercise1.conf.j2 dest=/etc/apache2/sites-available/{{ web.exercise1.domain }}.conf
  tags: apache2

- name: Apache2 | Add vhost for exercise-2
  template: src=vhost-exercise2.conf.j2 dest=/etc/apache2/sites-available/{{ web.exercise2.domain }}.conf
  tags: apache2

- name: Apache2 | Activate vhost
  command: a2ensite {{ web.exercise1.domain }}.conf {{ web.exercise2.domain }}.conf
  tags: apache2
  notify: Restart apache